---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qircuitc/qircuitapp
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/rsync -a --delete app/ $DEPLOYPATH/app/
    - /bin/rsync -a --delete static/ $DEPLOYPATH/static/
    - /bin/rsync -a --delete templates/ $DEPLOYPATH/templates/
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp seed.py $DEPLOYPATH
    - /bin/cp schema_sqlite.sql $DEPLOYPATH
    - /bin/cp DEPLOYMENT.md $DEPLOYPATH
    - /home/qircuitc/virtualenv/qircuitapp/3.11/bin/pip install -r $DEPLOYPATH/requirements.txt
    - cd $DEPLOYPATH && /home/qircuitc/virtualenv/qircuitapp/3.11/bin/python seed.py
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
