---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qircuitc/qircuitapp
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/rsync -a --delete app/ $DEPLOYPATH/app/
    - /bin/rsync -a --delete static/ $DEPLOYPATH/static/
    - /bin/rsync -a --delete templates/ $DEPLOYPATH/templates/
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp seed.py $DEPLOYPATH
    - /bin/cp schema_sqlite.sql $DEPLOYPATH
    - /bin/cp schema_postgres.sql $DEPLOYPATH
    - /bin/cp .htaccess /home/qircuitc/public_html/.htaccess
    - export VENV_BASE=/home/qircuitc/virtualenv/qircuitapp
    - PIP=""; PYTHON=""; for v in 3.11 3.10 3.9 3.8; do if [ -x "$VENV_BASE/$v/bin/pip" ]; then PIP="$VENV_BASE/$v/bin/pip"; PYTHON="$VENV_BASE/$v/bin/python"; break; fi; done
    - if [ -n "$PIP" ]; then $PIP install -r $DEPLOYPATH/requirements.txt; fi
    - if [ -n "$PYTHON" ]; then cd $DEPLOYPATH && $PYTHON seed.py; fi
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
