---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qircuitc/public_html/Qircuit/
    - /bin/rsync -a --delete app/ $DEPLOYPATH/app/
    - /bin/rsync -a --delete static/ $DEPLOYPATH/static/
    - /bin/rsync -a --delete templates/ $DEPLOYPATH/templates/
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp DEPLOYMENT.md $DEPLOYPATH
    - /home/qircuitc/virtualenv/public_html/Qircuit/3.11/bin/pip install -r $DEPLOYPATH/requirements.txt
    - /home/qircuitc/virtualenv/public_html/Qircuit/3.11/bin/python $DEPLOYPATH/seed.py
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
